syntax = "proto3";

option csharp_namespace = "Discount.Grpc";

package discount;

// The discount service definition.
service DiscountProtoService {
  
  //Discount CRUD opérations
  rpc GetDiscountByCode (GetDiscountRequest) returns (CouponModel);
  rpc GetDiscountByProductName (GetDiscountRequest) returns (CouponModel);
  rpc CreateDiscount (CreateDiscountRequest) returns (CouponModel);
  rpc UpdateDiscount (UpdateDiscountRequest) returns (CouponModel);
  rpc DeleteDiscount (DeleteDiscountRequest) returns (DeleteDiscountResponse);
  rpc ValidateDiscount (ValidateDiscountRequest) returns (ValidateDiscountResponse);
  
  //Get discounts by product
  rpc GetDiscountsByProduct (GetDiscountsByProductRequest) returns (GetDiscountsByProductResponse);
}

message GetDiscountRequest {
  string code = 1;
  string productName = 2;
}

message CouponModel {
  int32 id = 1;
  string productName = 2;
  string description = 3;
  double value = 4;
  string code = 5;
  DiscountType type = 6;
  double minimumOrderAmount = 7;
  bool isCumulative = 8;
  DiscountStatus status = 9;
  string startDate = 10;
  string endDate = 11;
}

enum DiscountStatus {
  UPCOMING = 0;
  ACTIVE = 1;
  EXPIRED = 2;
  DISABLED = 3;
}

enum DiscountType {
  FIXED_AMOUNT = 0;
  PERCENTAGE = 1;
}

message CreateDiscountRequest {
  CouponModel coupon = 1;
}

message UpdateDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountResponse {
  bool success = 1;
}

message GetDiscountsRequest {
  DiscountStatus status = 1;
  int32 page = 2;
  int32 pageSize = 3;
}

message GetDiscountsResponse {
  repeated CouponModel coupons = 1;
  int32 totalCount = 2;
}

message GetDiscountsByProductRequest {
  string productId = 1;
}

message GetDiscountsByProductResponse {
  repeated CouponModel coupons = 1;
}

message ValidateDiscountRequest {
  string code = 1;
  double current_applied_discount_percentage = 2;
  bool is_product_already_discounted = 3;
  double order_amount = 4;
  string productName = 5;
}

message ValidateDiscountResponse {
  bool IsValid = 1;
  string Message = 2;
  double AdjustedDiscountValue = 3;
}