syntax = "proto3";

option csharp_namespace = "Discount.Grpc";

package discount;

// The discount service definition.
service DiscountProtoService {
  
  //Discount CRUD opérations
  rpc GetDiscount (GetDiscountRequest) returns (CouponModel);
  rpc CreateDiscount (CreateDiscountRequest) returns (CouponModel);
  rpc UpdateDiscount (UpdateDiscountRequest) returns (CouponModel);
  rpc DeleteDiscount (DeleteDiscountRequest) returns (DeleteDiscountResponse);
}

message GetDiscountRequest {
  string productName = 1;
}

message CouponModel {
  int32 id = 1;
  string code = 2;
  string description = 3;
  double value = 4;
  DiscountType type = 5;
  double minimumOrderAmount = 6;
  bool isCumulative = 7;
  DiscountStatus status = 8;
  string startDate = 9;
  string endDate = 10;
}

enum DiscountStatus {
  UPCOMING = 0;
  ACTIVE = 1;
  EXPIRED = 2;
  DISABLED = 3;
}

enum DiscountType {
  FIXED_AMOUNT = 0;
  PERCENTAGE = 1;
}

message CreateDiscountRequest {
  CouponModel coupon = 1;
}

message UpdateDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountResponse {
  bool success = 1;
}

message GetDiscountsRequest {
  DiscountStatus status = 1;
  int32 page = 2;
  int32 pageSize = 3;
}

message GetDiscountsResponse {
  repeated CouponModel coupons = 1;
  int32 totalCount = 2;
}